development:
  adapter: postgresql
  encoding: unicode
  database: conjuguer_development
  pool: 5
  username: conjuguer
  password: 51julie2

test:
  adapter: postgresql
  encoding: unicode
  database: conjuguer_test
  pool: 5
  username: conjuguer
  password: 51julie2