# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Conjugaison.destroy_all
Vocabulaire.destroy_all
Erreur.destroy_all
v=Verbe.new('avere')

#liste = ['avere','lavorare','temere','credere','servire','finire','essere','venire','dovere','potere',\
#  'volere','sapere','stare','andare','dare','fare','dire','udire','uscire']
liste = ['lavorare']
liste.each do |f|
  @c = Conjugaison.create(infinitif: f, verbe: YAML.load(IO.read('db/verbes/'+f+'.yml')))
  @c.essais_verbe = 0
  @c.verbe.compteurs.each {|e| @c.essais_verbe += e}
  @c.save
end
liste = [\
["accouchement","un accouchement",8,"un parto"],
["accoucher","accoucher",8,"partorire"],
["adolescence","une adolescence",8,"un'adolescenza"],
["adresse","une adresse (postale)",8,"un indirizzo"],
["âge","un âge adulte",8,"un'età adulta"],
["âge","un âge (état civil)",8,"un'età"],
["âgée","une personne âgée",8,"una persona anziana"],
["agréable","agréable",8,"gradévole"],
["ami","un petit ami",8,"un ragazzo"],
["amie","une petite amie",8,"una ragazza"],
["amusant","amusant",8,"divertente"],
["anniversaire","fêter son anniversaire",8,"còmpiere gli anni"],
["anniversaire","un anniversaire",8,"un compleanno"],
["antipathique","antipathique",8,"antipàtico"],
["appeler","s'appeler",8,"chiamarsi"],
["barbe","une barbe",8,"una barba"],
["beau","beau",8,"bello"],
["beau-frère","un beau-frère",8,"un cognato"],
["beau-père","un beau-père (conjoint de la mère)",8,"un patrigno"],
["beau-père","le beau-père (père du conjoint)",8,"il suòcero"],
["beaux-parents","les beaux-parents",8,"i suòceri"],
["belle-mère","la belle-mère (mère du conjoint)",8,"la suòcera"],
["belle-mère","une belle-mère (conjoint du père)",8,"una matrigna"],
["belle-soeur","une belle-soeur",8,"una cognata"],
["blond","blond",8,"biondo"],
["bru","une bru",8,"una nuora"],
["brun","brun",8,"moro"],
["calme","calme",8,"calmo"],
["caractère","un caractère",8,"un caràttere"],
["carte","une carte d'identité",8,"una carta d'identità"],
["célibataire","une célibataire",8,"una single/una nùbile"],
["célibataire","un célibataire",8,"un single/un célibe"],
["châtain","châtain",8,"castano"],
["chauve","chauve",8,"calvo/pelato"],
["cheveux","les cheveux",8,"i capelli"],
["clair","clair",8,"claro"],
["colérique","colérique",8,"collérico"],
["compagne","une compagne",8,"una compagna"],
["compagnon","un compagnon",8,"un compagno"],
["comporter","se comporter",8,"comportarsi"],
["coordonnée","les coordonnées (état civil)",8,"i recàpiti"],
["costaud","costaud",8,"robusto"],
["court","court",8,"corto"],
["cousin","un cousin",8,"un cugino"],
["cousine","une cousine",8,"una cugina"],
["croissance","la croissance",8,"la créscita"],
["défaut","un défaut",8,"un difetto"],
["demi-frère","un demi-frère",8,"un fratellastro"],
["demi-soeur","une demi-soeur",8,"una sorellastra"],
["dépensier","dépensier",8,"spendaccione"],
["désagréable","désagréable",8,"sgradévole"],
["divorce","un divorce",8,"un divòrzio"],
["divorcé","divorcé",8,"divorziato"],
["divorcer","divorcer",8,"divorziare"],
["doux","doux",8,"dolce"],
["drôle","drôle",8,"buffo"],
["égoïste","égoïste",8,"egoista"],
["élancé","élancé",8,"slanciato"],
["élevé","bien élevé",8,"educato"],
["enfance","une enfance",8,"un'infànzia"],
["enfant","les enfants (parenté)",8,"i figli"],
["enfant (âge)","l'enfant",8,"il bambino/il bimbo"],
["ennuyeux","ennuyeux",8,"noioso"],
["enterrement","un enterrement",8,"un funerale"],
["époux","les époux",8,"i còniugi"],
["ex-femme","une ex-femme",8,"un'ex-mòglie"],
["ex-mari","un ex-mari",8,"un ex-marito"],
["extraverti","extraverti",8,"estroverso"],
["famille","la famille monoparentale",8,"la famìglia monoparentale"],
["femme","une femme",8,"una donna"],
["femme","la femme (épouse)",8,"la mòglie"],
["fiancé","un fiancé",8,"un fidanzato"],
["fiancée","une fiancée",8,"una fidanzata"],
["fiancer","se fiancer",8,"fidanzarsi"],
["fille","la fille/l'enfant",8,"la fìglia"],
["fille","une vieille fille",8,"una zitella"],
["fils","le fils/l'enfant",8,"il fìglio"],
["foncé","foncé",8,"scuro"],
["frère","un frère",8,"un fratello"],
["garçon","un vieux garçon",8,"uno scàpolo"],
["garde","une garde alternée",8,"un affidamento alternato"],
["gendre","un gendre",8,"un género"],
["généreux","généreux",8,"generoso"],
["grand","grand (taille)",8,"alto"],
["grandir","grandir",8,"créscere"],
["grand-mère","une grand-mère",8,"una nonna"],
["grand-père","un grand-père",8,"un nonno"],
["gros","gros",8,"grasso"],
["grossir","grossir",8,"ingrassare"],
["homme","un homme",8,"un uomo"],
["hypocrite","hypocrite",8,"ipòcrita"],
["individu","un individu",8,"un indivìduo"],
["intolérant","intolérant/intransigeant",8,"insofferente"],
["introverti","introverti",8,"introverso"],
["jeune","jeune",8,"giòvane"],
["joli","joli/mignon",8,"carino"],
["joyeux","joyeux",8,"allegro"],
["long","long",8,"lungo"],
["maigre","maigre",8,"magro"],
["maigrir","maigrir",8,"dimagrire"],
["maman","une maman",8,"una mamma"],
["manie","une manie",8,"una mania"],
["mari","un mari",8,"un marito"],
["mariage","un mariage",8,"un matrimònio"],
["marié","marié",8,"sposato/coniugato"],
["marié","les mariés",8,"gli sposi"],
["marier","se marier",8,"sposarsi"],
["menteur","menteur",8,"bugiardo"],
["mère","une mère",8,"una madre"],
["mince","mince",8,"snello"],
["moche","moche",8,"brutto"],
["mourir","mourir",8,"morire"],
["moustache","la moustache",8,"i baffi"],
["musclé","musclé",8,"muscoloso"],
["naissance","une naissance",8,"una nàscita"],
["naissance","un lieu de naissance",8,"un luogo di nàscita"],
["naissance","une date de naissance",8,"una data di nàscita"],
["naissance","né à",8,"nato a"],
["neveu","un neveu/un petit-fils",8,"un nipote"],
["nièce","une nièce/une petite-fille",8,"una nipote"],
["noces","les noces",8,"le nozze"],
["noir","noir",8,"nero"],
["nom","un nom de famille",8,"un cognome"],
["nouveau-né","un nouveau-né",8,"un neonato"],
["oeil","un oeil, les yeux",8,"un òcchio, gli occhi"],
["oncle","un oncle",8,"uno zio"],
["optimiste","optimiste",8,"ottimista"],
["papa","un papa",8,"un papà/un babbo"],
["papier","les papiers (état civil)",8,"i documenti"],
["parent","les parents",8,"i genitori"],
["passeport","un passeport",8,"un passaporto"],
["pension","la pension alimentaire",8,"gli alimenti"],
["père","un père",8,"un padre"],
["peser","peser",8,"pesare"],
["pessimiste","pessimiste",8,"pessimista"],
["petit","petit (taille)",8,"basso"],
["poids","un poids",8,"un peso"],
["poilu","poilu",8,"peloso"],
["prénom","un prénom",8,"un nome"],
["présenter","se présenter",8,"presentarsi"],
["qualité","une qualité",8,"una qualità/una virtù"],
["quitter","se quitter",8,"lasciarsi"],
["radin","radin",8,"tìrchio"],
["raffiné","raffiné",8,"raffinato"],
["remarier","se remarier",8,"risposarsi"],
["roux","roux",8,"rosso"],
["séduisant","séduisant",8,"attraente"],
["sembler","sembler",8,"sembrare"],
["séparation","une séparation",8,"una separazione"],
["séparé","séparé",8,"separato"],
["séparer","se séparer/rompre",8,"separarsi"],
["serviable","serviable",8,"serviziévole"],
["sexe","un sexe (état civil)",8,"un sesso"],
["sincère","sincère",8,"sincero"],
["soeur","une soeur",8,"una sorella"],
["surnom","un surnom",8,"un nomignolo/un soprannome"],
["susceptible","susceptible",8,"permaloso"],
["sympathique","sympatique",8,"simpàtico"],
["taciturne","taciturne",8,"taciturno"],
["taille","une taille (aspect physique)",8,"un'altezza"],
["tante","une tante",8,"una zia"],
["tempérament","un tempérament",8,"un'ìndole"],
["timide","timide",8,"tìmido"],
["trapu","trapu",8,"tozzo/tarchiato"],
["tutelle","en tutelle",8,"in affidamento"],
["union","l'union libre",8,"la còppia di fatto"],
["vaniteux","vaniteux",8,"vanitoso"],
["veuf","veuf",8,"védovo"],
["vieillesse","une vieillesse",8,"una vecchiàia"],
["vieillir","vieillir",8,"invecchiare"],
["vieux","vieux",8,"vécchio"],
["vivre","vivre ensemble",8,"convìvere"],
["vulgaire","vulgaire",8,"volgare"]
]

liste.each do |m|
  @m = Vocabulaire.create(mot_directeur: m[0], francais: m[1], compteur: m[2], italien: m[3])
  @m.save
end
